Repository sanders41/meilisearch-python-sdk, pull requests merged in 2024-12, with the labels that each got.

#1156 Remove option to pass strings to verify
  meilisearch_python_sdk/_client.py
Labels: breaking-change

#1163 Bump dependencies
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: skip-changelog, dependencies

#1168 Update renovate file and remove dependabot
  .github/dependabot.yaml
  .github/renovate.json5
Labels: skip-changelog

#1145 Update for Meilisearch v1.12
  meilisearch_python_sdk/_batch.py
  meilisearch_python_sdk/_client.py
  meilisearch_python_sdk/_http_requests.py
  meilisearch_python_sdk/_task.py
  meilisearch_python_sdk/_utils.py
  meilisearch_python_sdk/_version.py
  meilisearch_python_sdk/errors.py
  meilisearch_python_sdk/index.py
  meilisearch_python_sdk/models/batch.py
  meilisearch_python_sdk/models/settings.py
  meilisearch_python_sdk/models/task.py
  tests/conftest.py
  tests/test_async_client.py
  tests/test_async_index.py
  tests/test_async_search.py
  tests/test_client.py
  tests/test_index.py
  tests/test_search.py
  uv.lock
Labels: enhancement
