Repository sanders41/meilisearch-python-sdk, pull requests merged in 2025-02, with the labels that each got.

#1204 Remove dead code
  meilisearch_python_sdk/json_handler.py
Labels: skip-changelog

#1205 Use TYPE_CHECKING
  meilisearch_python_sdk/types.py
Labels: skip-changelog

#1206 Add option to pass parameters to get_batches
  meilisearch_python_sdk/_batch.py
  meilisearch_python_sdk/_client.py
  tests/test_async_client.py
  tests/test_client.py
Labels: enhancement

#1207 Fix types for uids and index_uids in cancel/delete tasks
  meilisearch_python_sdk/_client.py
  meilisearch_python_sdk/_task.py
Labels: bug

#1208 Bump version for release
  meilisearch_python_sdk/_version.py
Labels: skip-changelog

#1219 Update umami url
  docs/js/umami.js
Labels: skip-changelog

#1220 Add option to manually deploy docs
  .github/workflows/docs_publish.yml
Labels: skip-changelog

#1223 Allow None in the FacetSearchResults facet_query when passing an empty facet_query string.
  meilisearch_python_sdk/models/search.py
Labels: bug

#1224 Bump version for release
  meilisearch_python_sdk/_version.py
Labels: skip-changelog

#1209 Update for Meilisearch v1.13.0
  meilisearch_python_sdk/_client.py
  meilisearch_python_sdk/index.py
  meilisearch_python_sdk/models/search.py
  meilisearch_python_sdk/models/settings.py
  tests/conftest.py
  tests/test_async_index.py
  tests/test_async_search.py
  tests/test_index.py
  tests/test_search.py
Labels: enhancement

#1232 Bump version for release
  meilisearch_python_sdk/_version.py
Labels: skip-changelog

#1239 Add embedding information to IndexStats
  meilisearch_python_sdk/models/index.py
Labels: enhancement

#1240 Bump version for release
  meilisearch_python_sdk/_version.py
  uv.lock
Labels: skip-changelog
